/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/


#ifndef __ProtoLogin_Def_H__
#define __ProtoLogin_Def_H__


namespace CProto {
enum eClientUpdateFlag { /* 更新客户端标记 */
	UPDATE_NONEED = 0, /* 不需要更新 */
	UPDATE_TIPS = 1, /* 提示更新安装包 */
	UPDATE_FORCE = 2, /* 强制更新安装包 */
};

enum eDataType { /* 客户端纳入版本控制的数据类型 */
	DATA_USERATTR_DYNAMIC = 0, /* 主角动态数据 */
	DATA_USERATTR_DYNAMIC_RES , /* 主角动态资源数据 */
	DATA_USERATTR_STATIC , /* 主角静态数据 */
	DATA_ITEM_STATIC , /* 道具静态数据 */
	DATA_ITEM_DYNAMIC , /* 道具背包动态数据 */
	DATA_EQUIP_STATIC , /* 装备静态数据 */
	DATA_EQUIP_DYNAMIC , /* 装备背包动态数据 */
	DATA_EXPLORE_DYNAMIC , /* 探索动态数据 */
	DATA_EXPLORE_STATIC_SECTION , /* 探索章静态数据 */
	DATA_EXPLORE_STATIC_STAGE , /* 探索关卡静态数据 */
	DATA_GENERAL_STATIC , /* 武将静态数据 */
	DATA_GENERAL_DYNAMIC , /* 武将动态数据 */
	DATA_GENERAL_DYNAMIC_RES , /* 武将动态资源数据 */
	DATA_BATTLEARRAY_DYNAMIC , /* 阵容动态数据 */
	DATA_BATTLEMAP_STATIC , /* 阵容静态数据 */
	DATA_TITLE_DYNAMIC , /* 称号动态数据，优化可删除 */
	DATA_TITLE_STATIC , /* 称号静态数据 */
	DATA_SKILL_DYNAMIC , /* 技能静态数据 */
	DATA_SKILL_STATIC , /* 技能静态数据 */
	DATA_CARDTREE_STATIC , /* 卡牌谱静态数据 */
	DATA_BUTTON_STATIC , /* 按钮静态数据 */
	DATA_ACTIVITY_STATIC , /* 活动列表静态数据 */
	DATA_GENERAL_TRAVEL_STATIC , /* 武将云游静态数据 */
	DATA_STORE_STATIC , /* 商城静态数据 */
	DATA_STORY_STATIC , /* 剧情静态数据 */
	DATA_ADMIRE_STATIC , /* 好感度静态数据 */
	DATA_SENARIO_STATIC , /* 场景静态数据 */
	DATA_DROP_STATIC , /* 掉落静态数据 */
	DATA_CHAT_STATIC , /* 闲聊静态数据 */
	DATA_DATE_STATIC , /* 约会静态数据 */
	DATA_SYT_STATIC , /* 锁妖塔静态数据 */
	DATA_MOTION_STATIC , /* 行动力静态数据 */
	DATA_GENERAL_FUNCTION , /* 伙伴功能静态数据 */
	DATA_TYPE_NUM , /* 数据数量 */
};

enum eLoginStatusFlag { /* 登录验证状态标记 */
	LOGIN_OK = 0, /* 登录成功 */
	LOGIN_FAILED = 1, /* 登录验证失败需重新登录 */
	LOGIN_ERROR = 2, /* 登录错误 */
	LOGIN_GIDFAILED = 3, /* 登录分配gid失败 */
};

enum eLoginType { /* 登录帐号类型 */
	QQ = 0, /* QQ登录 */
	WeChat = 1, /* 微信登录 */
};

enum ePartStatus { /* 大区状态 */
	PART_WELL = 0, /* 良好 */
	PART_PERFECT = 1, /* 火爆 */
	PART_FULL = 2, /* 爆满 */
	PART_MAINTENANCE = 3, /* 维修 */
};

};


#endif

