/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/


#ifndef __ProtoExplore_Def_H__
#define __ProtoExplore_Def_H__


namespace CProto {
enum eUserExploreOResult { /* 探索操作返回值 */
	EOR_SUCCESS = 0, /* 成功 */
	EOR_FAILED_UNKNOWN , /* 未知失败 */
	EOR_FAILED_SECTION_LEVEL , /* 等级不满足章开启 */
	EOR_FAILED_PREMAP_STAR , /* 前置地图星数不满足 */
	EOR_FAILED_PRESTAGE_UNFINISH , /* 前置关卡未完成 */
	EOR_FAILED_PRESTAGE_STAR , /* 前置关卡星数不满足 */
	EOR_FAILED_FIGHT_TIMES , /* 可挑战次数已满 */
	EOR_FAILED_ELEMENT_GENERAL_NUM , /* 同元素武将数量不足 */
	EOR_FAILED_ENERGE , /* 精不足 */
	EOR_FAILED_SPIRIT , /* 神不足 */
	EOR_FAILED_SILVER , /* 银币不足 */
	EOR_FAILED_GOLD , /* 元宝不足 */
	EOR_FAILED_FULLITEMBAG , /* 道具背包已满 */
	EOR_FAILED_FULLEQUIPBAG , /* 装备背包已满 */
	EOR_FAILED_FULLGENERALSOUL , /* 元神已满 */
	EOR_FAILED_AWARD_MAPFULLSTAR , /* 奖励关需要满星通过才可领取 */
	EOR_FAILED_HIDE_OUTDATE , /* 隐藏关过期 */
};

enum eUserExploreDefine { /* 探索相关定义 */
	USER_EXPLORE_SECTION_NUM = 20, /* 探索章节数量 */
	USER_EXPLORE_SECTION_MAP_NUM = 10, /* 每个章节地图数量 */
	USER_EXPLORE_MAP_STAGE_NUM = 16, /* 每个地图关卡数量 */
	USER_EXPLORE_TOTAL_MAP_NUM = USER_EXPLORE_SECTION_NUM*USER_EXPLORE_SECTION_MAP_NUM, /* 所有探索地图数量 */
	USER_EXPLORE_TOTAL_STAGE_NUM = USER_EXPLORE_SECTION_NUM*USER_EXPLORE_SECTION_MAP_NUM*USER_EXPLORE_MAP_STAGE_NUM, /* 所有探索关卡数量 */
	USER_EXPLORE_TOTAL_ELITE_STAGE_NUM = USER_EXPLORE_SECTION_NUM*USER_EXPLORE_SECTION_MAP_NUM*3, /* 总精英关卡数量 */
	USER_EXPLORE_TOTAL_BOSS_STAGE_NUM = USER_EXPLORE_SECTION_NUM*USER_EXPLORE_SECTION_MAP_NUM, /* 总boss关卡数量 */
	USER_EXPLORE_TOTAL_HIDE_STAGE_NUM = 10, /* 总隐藏关卡数量 */
	USER_EXPLORE_TOTAL_AWARD_STAGE_NUM = USER_EXPLORE_SECTION_NUM*USER_EXPLORE_SECTION_MAP_NUM*3, /* 总奖励关卡数量 */
	USER_EXPLORE_MAX_DIRTY_STAGE_NUM = 10, /* 最多可置脏的关卡数量 */
};

enum eExploreSynClient { /* 探索同步数据类型 */
	USER_EXPLORE_ASC_SECTION_OPEN = 0, /* 章节开启标志 */
	USER_EXPLORE_ASC_MAP_OPEN , /* 地图开启标志 */
	USER_EXPLORE_ASC_STAGE_DATA , /* 关卡数据 */
	USER_EXPLORE_ASC_NUM , /*  */
};

enum eExploreStageClass { /* 探索关卡功能类型 */
	ESTAGE_CLASS_MAIN = 0, /* 主线 */
	ESTAGE_CLASS_BRANCH , /* 支线 */
	ESTAGE_CLASS_HIDE , /* 隐藏 */
};

enum eExploreStageType { /* 探索关卡类型 */
	ESTAGE_TYPE_ELITE = 0, /* 精英 */
	ESTAGE_TYPE_BOSS , /* boss */
	ESTAGE_TYPE_DRAMA , /* 剧情 */
	ESTAGE_TYPE_HIDE , /* 隐藏 */
	ESTAGE_TYPE_AWARD , /* 奖励 */
};

enum eExploreStageDataExSynFlag { /* 探索关卡扩展数据同步标示 */
	ESTAGE_DES_OPENSTATE = 0, /* 开启状态 */
	ESTAGE_DES_LEFTTIME , /* 剩余开启时间 */
	ESTAGE_DES_FIGHTTIMES , /* 战斗次数 */
	ESTAGE_DES_NUM = 8, /*  */
};

enum eExploreStageOpenState { /* 探索关卡开启状态 */
	ESTAGE_OPEN_HIDE = 0, /* 隐藏 */
	ESTAGE_OPEN_GREY , /* 灰化 */
	ESTAGE_OPEN_OPEN , /* 开启 */
};

};


#endif

