/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/


#ifndef __CProto_Def_H__
#define __CProto_Def_H__


namespace CProto {
enum { /* 数组或字符串最大长度定义 */
	MAX_NAME_LEN = 32, /* 名字字段最大长度 */
	MAX_LEN_SMALL = 64, /* 短字符串长度64字节 */
	MAX_LEN_LARGE = 1024, /* 长字符串长度1024字节 */
	MAX_LEN_QHTML = 4096, /* QHTML最大长度 */
	MAX_LEN_TABLE = 204800, /* 配表数据最大长度64K */
	MAX_USERGENERAL_NUM = 300, /* 所有武将数量 */
	MAX_USERGENERAL_SOUL_NUM = 300, /* 所有元神数量 */
	MAX_USEEQUIP_NUM = 500, /* 所有装备数量 */
	MAX_BUTTON_PARAM_NUM = 10, /* 单个按钮参数 */
	MAX_BATTLE_OBJ_NUM = 5, /* 战场中一方武将的最大叔 */
	MAX_BATTLE_DROP_ITEM_NUM = 5, /* 掉落内容个数 */
	MAX_RANK_NUM = 50, /* 积分榜排行列表 */
	MAX_BUTTON_NUM = 5, /* 按钮个数 */
};

enum eResDataSynType { /* 数组或字符串最大长度定义 */
	RESDATA_SYN_FULLDATA = 0, /* 全量资源数据 */
	RESDATA_SYN_DELTADATA , /* 增量资源数据 */
};

enum eChatTypeEnum { /* 聊天频道类型 */
	CHAT_INVALID = -1, /* 无效 */
	CHAT_NORMAL = 0, /* 综合频道 */
	CHAT_WORLD = 1, /* 世界频道 */
	CHAT_PRIVATE = 2, /* 私聊频道 */
	CHAT_SYSTEM = 3, /* 系统频道 */
	CHAT_MAX = 10, /* 频道类型最大值 */
};

enum eProtoMoneyType { /* 银两定义 */
	PROTO_MONEY_SILVER = 1, /* 银两 */
	PROTO_MONEY_GOLD = 2, /* 金币 */
};

enum eBattleType { /* 战斗类型 */
	PROTO_BATTLETYPE_INVALID = -1, /* 无效 */
	PROTO_BATTLETYPE_PVE = 0, /* PVE */
	PROTO_BATTLETYPE_PVP = 1, /* PVP */
	PROTO_BATTLETYPE_ACTIVITY_NORMAL = 2, /* 通用活动 */
	PROTO_BATTLETYPE_STORY = 3, /* 剧情 */
	PROTO_BATTLETYPE_SYT_PVE = 4, /* 锁妖塔pve */
	PROTO_BATTLETYPE_SYT_PVP = 5, /* 锁妖塔pvp */
	PROTO_BATTLETYPE_DATE = 6, /* 约会关 */
};

enum eRewardType { /* 奖励类型 */
	PROTO_BATTLEAWARD_INVALID = 0, /* 物品 */
	PROTO_BATTLEAWARD_GENERAL = 1, /* 武将 */
	PROTO_BATTLEAWARD_GENERALSOUL = 2, /* 元神 */
	PROTO_BATTLEAWARD_ITEM = 3, /* 物品 */
	PROTO_BATTLEAWARD_EQUIP = 4, /* 装备 */
	PROTO_BATTLEAWARD_SKILL = 5, /* 技能 */
	PROTO_BATTLEAWARD_TITLE = 6, /* 盒子 */
};

};


#endif

