/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/


#ifndef __ProtoContainer_Def_H__
#define __ProtoContainer_Def_H__


namespace CProto {
enum CONST_DEFINE { /* 常量定义 */
	PROTO_INVALID_VERSION = -1, /* 非法版本号 */
};

enum ITEM_TYPE { /* 物品类型 */
	ITEMS = 0, /* 道具 */
	EQUIPS = 1, /* 装备 */
};

enum PROTO_BANDTYPE { /* 物品绑定类型 */
	BAND_NOT = 0, /* 不绑定 */
	BAND_GET = 1, /* 获取绑定 */
	BAND_EQUIP = 2, /* 装备绑定 */
};

enum PROTO_BANDSTATUS { /* 物品绑定状态 */
	BAND_NO = 0, /* 未绑定 */
	BAND_YES = 1, /* 已绑定 */
};

enum ITEM_ATTR_SYN_CLIENT { /* 物品需要同步到客户端的属性 */
	ITEM_SYNC_FLAG_GRIDID = 0, /* 格子号 */
	ITEM_SYNC_FLAG_CHANGEFLAG , /* 属性变化 */
	ITEM_SYNC_FLAG_ITEMID , /* 物品ID */
	ITEM_SYNC_FLAG_GUID , /* 物品Guid */
	ITEM_SYNC_FLAG_OVERLAP , /* 物品该格子叠加数 */
	ITEM_SYNC_FLAG_TIMEOUT , /* 物品到期时间(UTC的秒数) */
	ITEM_SYNC_FLAG_BANDTYPE , /* 物品绑定类型 */
	ITEM_SYNC_FLAG_BANDSTATUS , /* 物品绑定状态 */
	ITEM_SYNC_FLAG_EQUIP_LVL_SOLID , /* 装备强化等级 */
	ITEM_SYNC_FLAG_EQUIP_LVL_GRADE , /* 装备升阶等级 */
	ITEM_SYNC_FLAG_EQUIP_GRADE_SPIRIT , /* 装备升阶器灵值 */
	ITEM_SYNC_FLAG_EQUIP_SIGNATTR , /* 装备贴符 */
	ITEM_SYNC_FLAG_EQUIP_SKILL_STATUS , /* 装备技能激活状态 */
	ITEM_SYNC_FLAG_EQUIP_ONOFF_INFO , /* 装备已装备未装备信息 */
	ITEM_SYNC_FLAG_MAX , /* 最大同步属性值 */
};

};


#endif

