/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/

#include "ProtoGeneralTravelDef.h"

#ifndef __ProtoGeneralTravel_H__ 
#define __ProtoGeneralTravel_H__ 

#include "CProto_Common.h"

#include "CProto.h"



namespace CProto {
/* 好友武将缘数据 */
struct stGeneralDataProto {
public:
    void Encode(unsigned char *buffer, unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer, unsigned int& bufferlen) throw (DecodeError);

    stGeneralDataProto();
    void SetDefault();

/* 好友guid */
    uint64_t friendGuid;
/* 好友武将ID */
    short friendGeneralID;
/* 是否有缘：1有；0无 */
    char hasFate;

private:
    unsigned int arraysize;
};
class XJCMD_CSC_GENERALTRAVEL_DETAILCS : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_CSC_GENERALTRAVEL_DETAILCS();
    void SetDefault();

    
/* 请求标记，无实际作用 */
    char detailRequest;

private:
    unsigned int arraysize;
};
class XJCMD_CSC_GENERALTRAVEL_DETAILSC : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_CSC_GENERALTRAVEL_DETAILSC();
    void SetDefault();

    
/* 当前状态 */
    eStateDetailType travelState;
/* 当前档次 */
    char travelPlace;
/* 今日已云游次数 */
    char travelTimes;
/* 今日可云游次数上限 */
    char travelTimeMAX;
/* 云游剩余时间，当travelState为STATE_TYPE_TRAVELLING时有效，距1900-0-0 0:0:0的秒数 */
    int remainTime;
/* 伙伴ID */
    short generalID;
/* 好友GUiD */
    uint64_t friendGUID;
/* 好友伙伴ID */
    short friendGeneralID;
/* 本次云游是否有缘，0无缘，1有缘 */
    char hasFate;

private:
    unsigned int arraysize;
};
class XJCMD_CSC_GENERALTRAVEL_USEMONEYCS : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_CSC_GENERALTRAVEL_USEMONEYCS();
    void SetDefault();

    
/* 当前档次 */
    char travelPlace;
/* 金钱类型 */
    eMoneyType monyeType;

private:
    unsigned int arraysize;
};
class XJCMD_CSC_GENERALTRAVEL_USEMONEYSC : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_CSC_GENERALTRAVEL_USEMONEYSC();
    void SetDefault();

    
/* 刷新结果 */
    eStateRetType useRet;
/* 当前档次 */
    char travelPlace;
/* 金钱类型 */
    eMoneyType monyeType;

private:
    unsigned int arraysize;
};
class XJCMD_CSC_GENERALTRAVEL_BEGINCS : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_CSC_GENERALTRAVEL_BEGINCS();
    void SetDefault();

    
/* 云游档次 */
    char travelPlace;
/* 伙伴ID */
    short generalID;
/* 好友GUiD */
    uint64_t friendGUID;
/* 好友伙伴ID */
    short friendGeneralID;

private:
    unsigned int arraysize;
};
class XJCMD_CSC_GENERALTRAVEL_BEGINSC : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_CSC_GENERALTRAVEL_BEGINSC();
    void SetDefault();

    
/* 当前档次 */
    char travelPlace;
/* 是否开始 */
    eStateRetType travellingState;
/* 云游剩余时间，当travelState为STATE_TYPE_TRAVELLING时有效，距1900-0-0 0:0:0的秒数 */
    int remainTime;
/* 本次云游是否有缘 */
    char hasFate;

private:
    unsigned int arraysize;
};
class XJCMD_CSC_GENERALTRAVEL_GETREWARDCS : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_CSC_GENERALTRAVEL_GETREWARDCS();
    void SetDefault();

    
/* 云游档次 */
    char travelPlace;

private:
    unsigned int arraysize;
};
class XJCMD_CSC_GENERALTRAVEL_GETREWARDSC : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_CSC_GENERALTRAVEL_GETREWARDSC();
    void SetDefault();

    
/* 当前档次 */
    char travelPlace;
/* 领奖结果 */
    eStateRetType getRet;

private:
    unsigned int arraysize;
};
class XJCMD_CSC_GENERALTRAVEL_FATELISTCS : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_CSC_GENERALTRAVEL_FATELISTCS();
    void SetDefault();

    
/* 上阵武将ID */
    short generalIDOwn;

private:
    unsigned int arraysize;
};
class XJCMD_CSC_GENERALTRAVEL_FATELISTSC : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_CSC_GENERALTRAVEL_FATELISTSC();
    void SetDefault();

    
/* 上阵武将ID */
    short generalIDOwn;
/* 好友缘列表，最大长度为好友列表长：50 */
    unsigned char friendFateList_arraylen;	stGeneralDataProto friendFateList[50];

private:
    unsigned int arraysize;
};
};


#endif

