/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/


#ifndef __ProtoUser_Def_H__
#define __ProtoUser_Def_H__


namespace CProto {
enum eProtoMaxNum { /* 数组或字符串最大长度定义 */
	PROTO_MAX_CARDTREE_NUM = 32, /* 卡牌谱系列最大数 */
};

enum eEnchantmentType { /* 角色需要同步到客户端的属性 */
	ENCHANTMENT_TYPE_NUM = 15, /* 结界类型数量 */
};

enum USER_ATTR_SYN_CLIENT { /* 角色需要同步到客户端的属性 */
	USER_ASC_NAME = 0, /* 昵称 */
	USER_ASC_FACE , /* 头像 */
	USER_ASC_SEX , /* 性别 */
	USER_ASC_LEVEL , /* 等级 */
	USER_ASC_EXP , /* 阅历 */
	USER_ASC_VIP_LEVEL , /* vip等级 */
	USER_ASC_SILVER , /* 银两 */
	USER_ASC_GOLD , /* 金币 */
	USER_ASC_CRYSTAL , /* 晶玉 */
	USER_ASC_ENERGY , /* 精 */
	USER_ASC_ENERGY_RECOVER_TIME , /* 精下次恢复时间 */
	USER_ASC_SPIRIT , /* 神 */
	USER_ASC_SPIRIT_RECOVER_TIME , /* 神下次恢复时间 */
	USER_ASC_ENCHANTMENT , /* 结界数据 */
	USER_ASC_YUANQI , /* 元气 */
	USER_ASC_RES , /* 资源数据 */
	USER_ASC_CARDTREE , /* 卡牌谱 */
	USER_ASC_COMBATPOWER , /* 战斗力 */
	USER_ASC_RARE_DRAW_TIMESTAMP , /* 高级抽卡时间错 */
	USER_ASC_EPIC_DRAW_TIMESTAMP , /* 特级抽卡时间戳 */
	USER_ASC_NUM , /* 角色属性总数 */
};

enum eCardTreeAwardType { /* 卡牌谱奖励枚举 */
	ETREEAWARD_TYPE_SOUL = 0, /* 奖励元神 */
	ETREEAWARD_TYPE_ITEM , /* 奖励道具 */
	ETREEAWARD_TYPE_EXP , /* 奖励经验 */
	ETREEAWARD_TYPE_MONEY , /* 奖励银两 */
	ETREEAWARD_TYPE_NUM , /* 奖励num */
};

enum EnchantmentECode { /* 结界错误代码 */
	EEC_UNKNOWN = -1, /*  */
	EEC_GOOD , /*  */
	EEC_INVALID_GENERAL_ID , /* 无效武将id */
	EEC_INVALID_GENERAL_CLASS , /* 无效的武将品质 */
	EEC_NOT_ENOUGH_SOUL , /* 元神不够 */
	EEC_GENERAL_NOT_OWN , /* 没有拥有这个武将 */
	EEC_CONSUME_FAILED , /* 消耗失败 */
	EEC_GENERAL_BUSY , /* 武将正在上阵, 援护, 云游 */
	EEC_YUANQI_OVERFLOW , /* 元气超过上限 */
	EEC_CRYSTAL_OVERFLOW , /* 晶玉超过上限 */
	EEC_REACH_MAX_LEVEL , /* 达到结界的最大等级 */
	EEC_LEVEL_NOT_SATISFY , /* 人物等级不满足 */
	EEC_NOT_ENOUGH_YUANQI , /* 元气不够 */
	EEC_NOT_ENOUGH_SILVER , /* 银两不够 */
};

};


#endif

