/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/


#ifndef __ProtoSkill_Def_H__
#define __ProtoSkill_Def_H__


namespace CProto {
enum { /* 阵法装备点定义 */
	PROTO_SKILL_NUM = 128, /* 技能列表的长度 */
	PROTO_SKILLITEM_TYPE_NUM = 5, /* 技能书种类 */
	PROTO_SKILL_SPECITEM_NUM = 3, /* 技能特殊道具个数 */
};

};


#endif

