/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/


#ifndef __ProtoSystemDialog_Def_H__
#define __ProtoSystemDialog_Def_H__


namespace CProto {
enum eSystemDlgTypeEnum { /* 系统框样式类型 */
	DAILOG_TYPE_NORMAL = -1, /* 异步普通样式 */
	DAILOG_TYPE_NORMAL_SYNC = 1, /* 同步普通样式 */
};

enum eSystemDlgRecycleKeyEnum { /* 系统框回传key类型，前后台约定占用的特殊key */
	Recycle_TYPE_INVALID = -1, /*  */
	Recycle_TYPE_STRING = 0, /* 需要解析字符串 */
	Recycle_TYPE_MAIN = 1, /* 跳转主页面 */
	Recycle_TYPE_ACTIVITY = 2, /* 发送活动请求，跳转活动页面 */
	Recycle_TYPE_SHOP = 3, /* 跳转商城页面 */
	Recycle_TYPE_CONTAINER = 4, /* 跳转到背包界面，KeyBuffer：4,容器类型（ITEM_CONTAINER_TYPE装备，道具，技能） */
	Recycle_TYPE_SOUL = 5, /* 跳转到武将元神界面，KeyBuffer：5,0 */
	Recycle_TYPE_SERVERSTART = 100, /* 100以后客户端无特殊处理，直接透传后台 */
};

enum eSystemDlgRecycleParamIndexEnum { /* 系统框回传不同类型Index含义 */
	Recycle_PARAM_KEY = 0, /* key类型 */
	Recycle_PARAM_ACTIVITY_ID = 1, /* 活动，ID */
	Recycle_PARAM_ACTIVITY_GUIDL = 2, /* 玩家guid low */
	Recycle_PARAM_ACTIVITY_GUIDH = 3, /* 玩家guid high */
	Recycle_PARAM_CONTAINER_TYPE = 1, /* 背包类型（ITEM_CONTAINER_TYPE） */
	Recycle_PARAM_MAX = 20, /* 最多定义20个回传参数 */
};

};


#endif

