/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/


#ifndef __ProtoMail_Def_H__
#define __ProtoMail_Def_H__


namespace CProto {
enum { /* 邮件相关最大数值定义，与存储相关，不可以更改 */
	MAIL_MAX_SYSTEM_MAIL_COUNT = 50, /* 系统邮件最大数 */
	MAIL_MAX_FRIEND_MAIL_COUNT = 50, /* 好友邮件最大数 */
	MAIL_MAX_ATTACH_FILE_COUNT = 4, /* 附件最大数 */
	MAIL_MAX_ATTACH_FILE_NAME = 128, /* 附件名最大长度 */
	MAIL_MAX_TITLE_LEN = 10, /* 标题字数上限 */
	MAIL_MAX_ATTACH_CONTENT_LEN = 60, /* 附件邮件文本内容字数上限 */
	MAIL_MAX_TEXT_CONTENT_LEN = 90, /* 普通文本字数上限 */
	MAIL_MAX_DESC = 20, /* 普通描述字数上限 */
};

enum eMailType { /* 邮件类型 */
	MAIL_TYPE_INVALID = -1, /* 无效类型 */
	MAIL_TYPE_SYSTEM = 0, /* 系统 */
	MAIL_TYPE_FRIENDS = 1, /* 好友 */
	MAIL_TYPE_EXE = 2, /* 可执行 */
};

enum eMailState { /* 邮件相关状态 */
	MAIL_STATE_UNREAD = 0, /* 未读 */
	MAIL_STATE_READ = 1, /* 已读 */
	MAIL_STATE_UNFULL = 2, /* 邮件未满 */
	MAIL_STATE_FULL = 3, /* 邮件已满 */
	MAIL_STATE_ALL = 4, /* 全量推送邮件列表 */
	MAIL_STATE_DELTA = 5, /* 增量推送邮件列表 */
	MAIL_STATE_GETATTACH = 6, /* 提取附件 */
};

enum eMailDeleteType { /* 删除邮件类型 */
	MAIL_Delete_One = 0, /* 删除1封 */
	MAIL_Delete_All = 1, /* 全部删除 */
};

enum eMailOpRet { /* 邮件操作结果类型 */
	MAIL_Op_Fail = 0, /* 失败 */
	MAIL_Op_Succ = 1, /* 成功 */
};

enum eMailBoxState { /* 邮件箱状态 */
	MAIL_BOX_INVALID = -1, /* 无效类型 */
	MAIL_BOX_NEW = 0, /* 新邮件 */
	MAIL_BOX_FULL = 1, /* 已满 */
	MAIL_BOX_UNREAD = 2, /* 未读 */
};

enum eExeMailType { /* 可执行邮件类型 */
	EXE_MAIL_TYPE_INVALID = -1, /* 无效类型 */
	EXE_MAIL_TYPE_SPEAK = 0, /* 禁言 */
	EXE_MAIL_TYPE_ADDITEM = 1, /* 增加道具 */
};

enum eAttachType { /* 附件类型 */
	ATTACH_TYPE_INVALID = -1, /* 无效类型 */
	ATTACH_TYPE_ITEM = 0, /* 道具 */
	ATTACH_TYPE_EQUIP = 1, /* 装备 */
	ATTACH_TYPE_SKILL = 2, /* 技能 */
	ATTACH_TYPE_GENERAL = 3, /* 武将 */
	ATTACH_TYPE_MONEY = 4, /* 金钱 */
};

};


#endif

