/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/


#ifndef __ProtoSenario_Def_H__
#define __ProtoSenario_Def_H__


namespace CProto {
enum eSenarioNum { /* 场景相关常量最值 */
	E_SENARIO_NUM_MAX = 40, /* 最多场景数 */
	E_SENARIO_HIDE_STAGE_NUM = 10, /* 同一场景同时最多隐藏关个数 */
	E_SENARIO_DROP_NUM = 2, /* 同一场景同时最多掉落个数 */
};

enum eSenarioState { /* 场景状态 */
	E_SENARIO_STATE_UNLOCK = 0, /* 是否开启 */
	E_SENARIO_STATE_FIRSTOPEN = 1, /* 首开 */
	E_SENARIO_STATE_ENTER = 2, /* 今日进入 */
	E_SENARIO_STATE_MAX_NUMNUM = 8, /* 存储相关 */
};

enum eSenarioType { /* 场景类型 */
	E_SENARIO_TYPE_INVALID = 0, /* 无效 */
	E_SENARIO_TYPE_BOSS = 1, /* boss */
	E_SENARIO_TYPE_STORY = 2, /* 剧情 */
	E_SENARIO_TYPE_DATE = 3, /* 约会 */
};

};


#endif

