/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/


#ifndef __ProtoActivity_Def_H__
#define __ProtoActivity_Def_H__


namespace CProto {
enum ACTIVITY_ACTIVE_FLAG { /* 活动开启标记 */
	AAF_CLOSE = 0, /* 关闭 */
	AAF_OPEN = 1, /* 开启 */
};

enum ACTIVITY_STATE_FLAG { /* 活动状态标记 */
	ASF_DISABLE = 0, /* 活动不可参加 */
	ASF_ENABLE = 1, /* 活动可参加 */
	ASF_FINISH = 2, /* 活动已完成 */
};

enum ACTIVITY_DISPLAY_FLAG { /* 活动有效(显示)标记 */
	ADF_DISABLE = 0, /* 活动不显示 */
	ADF_ENABLE = 1, /* 活动显示 */
};

enum ACTIVITY_COMMAND_ID { /* 活动命令ID */
	ACI_DETAILS = 1, /* 活动详情 */
};

enum ACTIVITY_CONST { /* 活动相关的常量 */
	MAX_ACTIVITY_COMMAND_PARAM_INT_NUM = 10, /* 活动通用参数的INT最大个数 */
	MAX_ACTIVITY_COMMAND_PARAM_GUID_NUM = 5, /* 活动通用参数的GUID最大个数 */
	MAX_ACTIVITY_COMMAND_PARAM_QHTML_NUM = 10, /* 活动通用参数的qhtml最大个数 */
};

};


#endif

