/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/

#include "ProtoSenarioDef.h"

#ifndef __ProtoSenario_H__ 
#define __ProtoSenario_H__ 

#include "CProto_Common.h"

#include "CProto.h"



namespace CProto {
/* 场景隐藏关卡数据 */
struct stHideStage {
public:
    void Encode(unsigned char *buffer, unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer, unsigned int& bufferlen) throw (DecodeError);

    stHideStage();
    void SetDefault();

/* 关卡id */
    short stageId;
/* 关卡类型 */
    eSenarioType senarioType;
/* 剩余时间 */
    int remainTime;
/* 该约会关伙伴Id，boss关为-1 */
    short generalId;

private:
    unsigned int arraysize;
};
/* 场景数据 */
struct stSenarioData {
public:
    void Encode(unsigned char *buffer, unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer, unsigned int& bufferlen) throw (DecodeError);

    stSenarioData();
    void SetDefault();

/* 场景id，对应资源配置 */
    unsigned char senarioId;
/* 场景状态 */
    proto_vector<unsigned char> senarioState;
/* 场景内是否有翻箱倒柜 */
    proto_vector<short> senarioDrop;
/* 隐藏关卡数据 */
    proto_vector<stHideStage> stageInfo;

private:
    unsigned int arraysize;
};
class XJCMD_SC_SENARIO_SYNSC : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_SC_SENARIO_SYNSC();
    void SetDefault();

    
/* 动态协议数据版本号，确保客户端收包顺序 */
    char version_db;
/* 未开启隐藏boss关数目 */
    unsigned char bossEventNum;
/* 未开启隐藏剧情关数目 */
    unsigned char storyEventNum;
/* 未开启隐藏约会关数目 */
    unsigned char dateEventNum;
/* 是否有新伙伴加入 */
    unsigned char generalNew;
/* 同步的场景数据 */
    proto_vector<stSenarioData> senarioData;

private:
    unsigned int arraysize;
};
};


#endif

