/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/


#ifndef __ProtoPinJian_Def_H__
#define __ProtoPinJian_Def_H__


namespace CProto {
enum { /* 数组或字符串最大长度定义 */
	PINJIAN_MAX_FIGHT_USER_NUM = 4, /* 每次挑战的玩家数量 */
	PINJIAN_MAX_TOP_LIST_NUM = 50, /* 最多展示前多少名玩家信息 */
};

};


#endif

