/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/


#ifndef __ProtoFriend_Def_H__
#define __ProtoFriend_Def_H__


namespace CProto {
enum { /* 数组或字符串最大长度定义 */
	MAX_URL_LEN = 2000, /* 头像url长度 */
	MAX_NAME_EX_LEN = 128, /* QQ或微信名长度 */
	MAX_FRIENDPROTO_NUM = 50, /* 好友最大数量 */
	MAX_FRIEND_EVENT_NUM = 30, /* 好友动态最大条数值 */
	MAX_FRIEND_REQUEST_NUM = 20, /* 新朋友最大数量 */
	MAX_FRIEND_PRESENT = 100, /* 赠送最大数量 */
	MAX_FRIEND_GENAL_NUM = 5, /* 好友上阵武将最大数量 */
};

enum eFriendOpType { /* 好友相关操作 */
	OP_AGGRE_ADD = 0, /* 接受好友请求 */
	OP_FRIEND_REQUEST = 1, /* 请求添加好友 */
	OP_FRIEND_DELETE = 2, /* 删除好友 */
	OP_FRIEND_SENDPRESENT = 3, /* 给好友赠送 */
	OP_INVITE_QQFRIEND = 4, /* 邀请QQ好友 */
	OP_INVITE_WXFRIEND = 5, /* 邀请微信好友 */
	OP_FRIEND_CHAT = 6, /* 发起聊天 */
	OP_FRIEND_MAIL = 7, /* 发送邮件 */
};

enum eFriendEventType { /* 好友动态类型 */
	FRIEND_EVENT_INVALID = -1, /* 无效 */
	FRIEND_EVENT_LEVELUP = 0, /* 好友升级 */
	FRIEND_EVENT_ACHIEVMENT = 1, /* 好友获得成就 */
	FRIEND_EVENT_EQUIP = 2, /* 好友获得高级装备 */
	FRIEND_EVENT_GENERAL = 3, /* 好友获得高级武将 */
	FRIEND_EVENT_ACTIVITY = 4, /* 参加活动 */
	FRIEND_EVENT_CHALLENGE = 5, /* 切磋 */
};

enum eFriendNoticeNew { /* 有新的好友相关通知提醒 */
	FRIEND_NOTICE_INVALID = -1, /* 无效 */
	FRIEND_NOTICE_EVENT = 0, /* 好友动态 */
	FRIEND_NOTICE_REQUEST = 1, /* 好友添加申请 */
	FRIEND_NOTICE_RECOMMEND = 2, /* 好友推荐好友 */
	FRIEND_NOTICE_PRESENT = 3, /* 好友赠送 */
	FRIEND_NOTICE_ASC_NUM = 4, /*  */
};

enum eFriendGetPresentType { /* 获取好友奖励类型 */
	FRIEND_PRESENT_INVALID = -1, /* 无效 */
	FRIEND_PRESENT_ONE = 0, /* 送1个，回包XJCMD_CSC_FRIEND_GET_PRESENT */
	FRIEND_PRESENT_ALL = 1, /* 同步所有赠送列表 */
};

};


#endif

