/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/

#include "ProtoCharDef.h"

#ifndef __ProtoChar_H__ 
#define __ProtoChar_H__ 

#include "CProto_Common.h"

#include "CProto.h"



namespace CProto {
class XJCMD_CREATECHARCS : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_CREATECHARCS();
    void SetDefault();

    
/* 角色名称 */
    unsigned short m_Name_arraylen;	char m_Name[MAX_NAME_LEN];
/* 角色性别 1==男 2==女 */
    unsigned char m_Sex;
/* 角色门派 */
    unsigned char m_MenPai;

private:
    unsigned int arraysize;
};
class XJCMD_CREATECHARSC : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_CREATECHARSC();
    void SetDefault();

    
/* 返回码 0==成功 else=失败 */
    unsigned char m_Ret;
/* 返回提示语 */
    unsigned short m_ErrMsg_arraylen;	char m_ErrMsg[MAX_LEN_SMALL];
/* guid */
    uint64_t m_Guid;

private:
    unsigned int arraysize;
};
class XJCMD_DELETECHARCS : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_DELETECHARCS();
    void SetDefault();

    
/* 角色Guid */
    uint64_t m_Guid;
/* 删除类型 */
    unsigned char m_DelType;

private:
    unsigned int arraysize;
};
class XJCMD_DELETECHARSC : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_DELETECHARSC();
    void SetDefault();

    
/* 返回码 0==成功 else=失败 */
    unsigned char m_Ret;
/* 返回提示语 */
    unsigned short m_ErrMsg_arraylen;	char m_ErrMsg[MAX_LEN_SMALL];
/* 删除类型 */
    unsigned char m_DelType;
/* 角色Guid */
    uint64_t m_Guid;

private:
    unsigned int arraysize;
};
class XJCMD_CANCELDELETECHARCS : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_CANCELDELETECHARCS();
    void SetDefault();

    
/* 角色Guid */
    uint64_t m_Guid;

private:
    unsigned int arraysize;
};
class XJCMD_CANCELDELETECHARSC : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_CANCELDELETECHARSC();
    void SetDefault();

    
/* 返回码 0==成功 else=失败 */
    unsigned char m_Ret;
/* 返回提示语 */
    unsigned short m_ErrMsg_arraylen;	char m_ErrMsg[MAX_LEN_SMALL];
/* 角色Guid */
    uint64_t m_Guid;

private:
    unsigned int arraysize;
};
};


#endif

