/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/

#include "ProtoNoticeDef.h"

#ifndef __ProtoNotice_H__ 
#define __ProtoNotice_H__ 

#include "CProto_Common.h"

#include "CProto.h"



namespace CProto {
class XJCMD_CSC_SYSTEM_NOTICECS : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_CSC_SYSTEM_NOTICECS();
    void SetDefault();

    
/* 客户端版本号 */
    unsigned char clientVersion_arraylen;	char clientVersion[MAX_LEN_SMALL];

private:
    unsigned int arraysize;
};
class XJCMD_CSC_SYSTEM_NOTICESC : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_CSC_SYSTEM_NOTICESC();
    void SetDefault();

    
/* 客户端版本号 */
    unsigned char clientVersion_arraylen;	char clientVersion[MAX_LEN_SMALL];
/* 公告内容数组 */
    unsigned short qhtmlcontent_arraylen;	stQhtml qhtmlcontent[MAX_NOTICE_NUM];

private:
    unsigned int arraysize;
};
};


#endif

