/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/


#ifndef __ProtoSystemTips_Def_H__
#define __ProtoSystemTips_Def_H__


namespace CProto {
enum eSystemTipShowEnum { /* 系统消息显示类型 */
	TIP_TYPE_NORMAL = 0, /* 上居中提示 */
	TIP_TYPE_ROLLING = 1, /* 上居中滚动提示 */
};

enum eSystemAwardType { /* 系统奖励类型 */
	AwardType_Invalid = -1, /*  */
	AwardType_Exp = 0, /* 奖励经验 */
	AwardType_Money = 1, /* 奖励金钱 */
	AwardType_Item = 2, /* 奖励物品 */
	AwardType_Soul = 3, /* 奖励元神 */
	AwardType_Title = 4, /* 奖励称号 */
	AwardType_Jing = 5, /* 奖励精 */
	AwardType_Shen = 6, /* 奖励神 */
	AwardType_GoodWill = 7, /* 奖励好感度 */
	AwardType_Skill = 8, /* 奖励技能 */
	AwardType_Max = 9, /*  */
};

enum eSystemHighlightMsgType { /* 系统醒目提示消息类型 */
	HighlightMsgType_Invalid = -1, /*  */
	HighlightMsgType_MainTitle = 0, /* 主提示 */
	HighlightMsgType_SubTitle = 1, /* 副提示 */
	HighlightMsgType_Max = 2, /*  */
};

};


#endif

