/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/


#ifndef __ProtoChat_Def_H__
#define __ProtoChat_Def_H__


namespace CProto {
enum { /* 聊天最大条数值 */
	MAX_CHAT_NUM = 512, /* 最大条数值 */
};

};


#endif

