/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/

#include "ProtoDefineDef.h"

#ifndef __ProtoDefine_H__ 
#define __ProtoDefine_H__ 

#include "CProto_Common.h"

#include "CProto.h"



namespace CProto {
};


#endif

