/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/

#include "ProtoLogDef.h"

#ifndef __ProtoLog_H__ 
#define __ProtoLog_H__ 

#include "CProto_Common.h"

#include "CProto.h"



namespace CProto {
/* 日志数据单元 */
struct stLogUnit {
public:
    void Encode(unsigned char *buffer, unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer, unsigned int& bufferlen) throw (DecodeError);

    stLogUnit();
    void SetDefault();

/* 英文字段名(最大255字符) */
    proto_string<0> name;
/* 字段值(最大1024字符) */
    proto_string<0> value;

private:
    unsigned int arraysize;
};
class XJCMD_CS_LOGCS : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_CS_LOGCS();
    void SetDefault();

    
/* 日志分类名称(英文最大255字符) */
    proto_string<0> logname;
/* 日志的所有字段数组 */
    unsigned short logunits_arraylen;	stLogUnit logunits[255];

private:
    unsigned int arraysize;
};
};


#endif

