/********************************************************************
 * This file is generated by program cap
 * Please do not change it directly
 * 
 * protocol name: CProto
 * protocol version: 1.0
 * protocol author:   
 * protocol desc: 仙剑卡牌客户端后台交互协议-控制协议
 *
 * history:
 * 2013-02-22 : 创建 (V1.0)
********************************************************************/

#include "ProtoSystemDialogDef.h"

#ifndef __ProtoSystemDialog_H__ 
#define __ProtoSystemDialog_H__ 

#include "CProto_Common.h"

#include "CProto.h"



namespace CProto {
/* 弹出框按钮附带信息 */
struct stSystemDlgBtnInfo {
public:
    void Encode(unsigned char *buffer, unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer, unsigned int& bufferlen) throw (DecodeError);

    stSystemDlgBtnInfo();
    void SetDefault();

/* 命令key */
    int btn_key;
/* 命令参数 */
    proto_string<0> params;

private:
    unsigned int arraysize;
};
class XJCMD_SC_SYSTEM_DIALOGSC : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_SC_SYSTEM_DIALOGSC();
    void SetDefault();

    
/* 对话框处理的key */
    unsigned short key;
/* 是否有关闭按钮 */
    char hasClose;
/* 是否有标题 */
    char hasTitle;
/* 标题名 */
    proto_string<0> titleName;
/* 是否有左按钮 */
    char hasLftButton;
/* 左按钮名 */
    proto_string<0> lftButtonName;
/* 左按钮key */
    proto_vector<char> lftButtonKey;
/* 是否有右按钮 */
    char hasRgtButton;
/* 右按钮名 */
    proto_string<0> rgtButtonName;
/* 右按钮key */
    proto_vector<char> rgtButtonKey;
/* 对话框内容 */
    stQhtml dlgContent;

private:
    unsigned int arraysize;
};
class XJCMD_CS_SYSTEM_RECYCLECHECKCS : public PackBody{
public:
    static int GetCommandID();
    void Encode(unsigned char *buffer,unsigned int& buffersize) throw (EncodeError);
    void Decode(const unsigned char* buffer,unsigned int& bufferlen) throw (DecodeError);
    int CommandID();

    XJCMD_CS_SYSTEM_RECYCLECHECKCS();
    void SetDefault();

    
/* 客户端回传参数 */
    proto_string<0> paramString;

private:
    unsigned int arraysize;
};
};


#endif

